# Generated by Django 4.2.5 on 2023-09-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('vigencia', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Tira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelita.categoria')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelita.jugador')),
                ('tira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuelita.tira')),
            ],
        ),
    ]
